### ISSUE TITLE
Meet with Brian to Discuss Semantic Analysis Ideas

### ISSUE THREAD

**Issue by shellebusch2** [shellebusch2/DSAllo#14]
- [x] schedule meeting

- [ ] have meeting

MEETING AGENDA
- semantic analysis for complaint type, urgency, and department
- assigning complaints to individual? or team
-  if assigning to team... does the market db have a list of teams assigned to that market?

**Comment by ekonnath** [comment]
Ask Brian about ALLO Support Agents submitting — should it be separate form or should be included in Tally

**Comment by ekonnath** [comment]
Ask Brian if market database has teams assigned to each market

**Comment by ekonnath** [comment]
Ask Brian if we are assigning complaint to individual or to complaint team

**Comment by ekonnath** [comment]
Takeaways from Brian's interview:
- Brian admits that semantic analysis would be very complicated, costly to set up
- Brian suggested redesigning the form to automatically populate some of these automated database fields
- We need to create/use config databases (complaint types, assignment teams, markets, any others needed)
- For populating the Complaint Types database, we should reach out to Ed
- For populating config databases(specifically complaint types and assignment teams), we should populate them a bit (but not to full capacity), then hand them off to ALLO staff so they can populate the rest of the database
- There are certain issues that come in that need to be responded to and resolved in a certain amount of time (by law). These issues will likely be under the "urgent" category and should be tagged as so
- (not a priority) Brian wanted us to eventually take a peek at grid.is because it may be easier to integrate into notion than deepnote, however the analysis does not automatically refresh so we will need to figure out how to do that
